# Generated by Django 4.2.7 on 2025-11-08 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_minima', models.FloatField(default=22, help_text='Temperatura mínima óptima en °C')),
                ('temp_maxima', models.FloatField(default=30, help_text='Temperatura máxima óptima en °C')),
                ('humedad_minima', models.FloatField(default=70, help_text='Humedad mínima óptima en %')),
                ('humedad_maxima', models.FloatField(default=85, help_text='Humedad máxima óptima en %')),
                ('humedad_suelo_minima', models.FloatField(default=40, help_text='Humedad suelo mínima óptima en %')),
                ('humedad_suelo_maxima', models.FloatField(default=80, help_text='Humedad suelo máxima óptima en %')),
                ('radiacion_minima', models.FloatField(default=600, help_text='Radiación solar mínima óptima en W/m²')),
                ('radiacion_maxima', models.FloatField(default=1000, help_text='Radiación solar máxima óptima en W/m²')),
                ('intervalo_sincronizacion', models.IntegerField(default=300, help_text='Intervalo de sincronización en segundos')),
                ('activa_api_externa', models.BooleanField(default=True, help_text='¿Activar sincronización con API externa?')),
                ('activar_predicciones', models.BooleanField(default=True, help_text='¿Activar generación de predicciones?')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'db_table': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='DatosMeteorologicos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperatura', models.FloatField(help_text='Temperatura en °C', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('humedad', models.FloatField(help_text='Humedad relativa en %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('humedad_suelo', models.FloatField(help_text='Humedad del suelo en %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('radiacion_solar', models.FloatField(help_text='Radiación solar en W/m²', validators=[django.core.validators.MinValueValidator(0)])),
                ('precipitacion', models.FloatField(default=0, help_text='Precipitación en mm')),
                ('presion', models.FloatField(blank=True, help_text='Presión atmosférica en hPa', null=True)),
                ('velocidad_viento', models.FloatField(default=0, help_text='Velocidad del viento en m/s')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Fecha y hora del dato')),
                ('fuente', models.CharField(choices=[('api_externa', 'API Externa'), ('csv', 'CSV Importado'), ('sensor', 'Sensor IoT'), ('manual', 'Entrada Manual')], default='api_externa', help_text='Origen del dato meteorológico', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos Meteorológicos',
                'verbose_name_plural': 'Datos Meteorológicos',
                'db_table': 'datos_meteorologicos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('administrativo', 'Administrativo')], default='estudiante', help_text='Rol del usuario en el sistema', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cultivo', models.CharField(help_text='Tipo de cultivo para la predicción', max_length=100)),
                ('viabilidad', models.FloatField(help_text='Viabilidad del cultivo en %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prediccion_temperatura', models.FloatField(blank=True, help_text='Temperatura predicha en °C', null=True)),
                ('prediccion_humedad', models.FloatField(blank=True, help_text='Humedad predicha en %', null=True)),
                ('prediccion_precipitacion', models.FloatField(blank=True, help_text='Precipitación predicha en mm', null=True)),
                ('confianza', models.FloatField(help_text='Confianza de la predicción en %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('modelo_version', models.CharField(default='1.0', help_text='Versión del modelo ML utilizado', max_length=50)),
                ('datos', models.ForeignKey(help_text='Datos meteorológicos origen de la predicción', on_delete=django.db.models.deletion.CASCADE, to='api.datosmeteorologicos')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'db_table': 'predicciones',
                'ordering': ['-generado_en'],
            },
        ),
        migrations.CreateModel(
            name='ExportacionCSV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo CSV exportado', max_length=255)),
                ('ruta', models.CharField(help_text='Ruta donde se guardó el archivo', max_length=500)),
                ('cantidad_registros', models.IntegerField(help_text='Número de registros en el CSV')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha inicio de los datos exportados')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha fin de los datos exportados')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(help_text='Usuario que realizó la exportación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Exportación CSV',
                'verbose_name_plural': 'Exportaciones CSV',
                'db_table': 'exportaciones_csv',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='datosmeteorologicos',
            index=models.Index(fields=['-timestamp'], name='datos_meteo_timesta_5a1a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='datosmeteorologicos',
            index=models.Index(fields=['fuente'], name='datos_meteo_fuente_d9f36e_idx'),
        ),
    ]
