# Generated by Django 4.2.7 on 2025-11-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionSistema',
        ),
        migrations.RemoveField(
            model_name='exportacioncsv',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='prediccion',
            name='datos',
        ),
        migrations.DeleteModel(
            name='DatosMeteorologicos',
        ),
        migrations.DeleteModel(
            name='ExportacionCSV',
        ),
        migrations.DeleteModel(
            name='Prediccion',
        ),
    ]
